spring:
  codec:
    max-in-memory-size: 2MB
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-headers: "*"
            # 半个月内都允许
            max-age: 1296000
            # 测试环境，全部允许
            allowedOriginPatterns: "*"
            allowedOrigins:
              - "http://localhost:9527"
              - "http://localhost:9527"
              - "http://localhost:9528"
              - "http://localhost:9529"
              - "http://:9527"
            allowedMethods:
              - GET
              - POST
              - PUT
              - OPTIONS
              - DELETE
      discovery:
        locator:
          # 开启服务注册和发现
          enabled: true
          # 不手动写路由的话，swagger整合不了...
      routes:
        - id: mall4cloud-rbac
          uri: lb://mall4cloud-rbac
          predicates:
            - Path=/mall4cloud_rbac/**
          filters:
            - RewritePath=/mall4cloud_rbac(?<segment>/?.*), $\{segment}
        - id: mall4cloud-auth
          uri: lb://mall4cloud-auth
          predicates:
            - Path=/mall4cloud_auth/**
          filters:
            - RewritePath=/mall4cloud_auth(?<segment>/?.*), $\{segment}
        - id: mall4cloud-multishop
          uri: lb://mall4cloud-multishop
          predicates:
            - Path=/mall4cloud_multishop/**
          filters:
            - RewritePath=/mall4cloud_multishop(?<segment>/?.*), $\{segment}
        - id: mall4cloud-biz
          uri: lb://mall4cloud-biz
          predicates:
            - Path=/mall4cloud_biz/**
          filters:
            - RewritePath=/mall4cloud_biz(?<segment>/?.*), $\{segment}
        - id: mall4cloud-product
          uri: lb://mall4cloud-product
          predicates:
            - Path=/mall4cloud_product/**
          filters:
            - RewritePath=/mall4cloud_product(?<segment>/?.*), $\{segment}
        - id: mall4cloud-user
          uri: lb://mall4cloud-user
          predicates:
            - Path=/mall4cloud_user/**
          filters:
            - RewritePath=/mall4cloud_user(?<segment>/?.*), $\{segment}
        - id: mall4cloud-order
          uri: lb://mall4cloud-order
          predicates:
            - Path=/mall4cloud_order/**
          filters:
            - RewritePath=/mall4cloud_order(?<segment>/?.*), $\{segment}
        - id: mall4cloud-platform
          uri: lb://mall4cloud-platform
          predicates:
            - Path=/mall4cloud_platform/**
          filters:
            - RewritePath=/mall4cloud_platform(?<segment>/?.*), $\{segment}
        - id: mall4cloud-search
          uri: lb://mall4cloud-search
          predicates:
            - Path=/mall4cloud_search/**
          filters:
            - RewritePath=/mall4cloud_search(?<segment>/?.*), $\{segment}
        - id: mall4cloud-payment
          uri: lb://mall4cloud-payment
          predicates:
            - Path=/mall4cloud_payment/**
          filters:
            - RewritePath=/mall4cloud_payment(?<segment>/?.*), $\{segment}
knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      version: openapi3
      enabled: true